<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gift extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'icon',
        'price',
        'description',
        'is_active',
        'sort_order',
    ];

    protected $casts = [
        'price' => 'decimal:2',
        'is_active' => 'boolean',
        'sort_order' => 'integer',
    ];

    /**
     * Get all transactions for this gift
     */
    public function transactions()
    {
        return $this->hasMany(GiftTransaction::class);
    }

    /**
     * Get total revenue generated by this gift
     */
    public function getTotalRevenueAttribute()
    {
        return $this->transactions()->sum('total_amount');
    }

    /**
     * Get total times this gift was sent
     */
    public function getTotalSentAttribute()
    {
        return $this->transactions()->sum('quantity');
    }

    /**
     * Scope to get only active gifts
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true)->orderBy('sort_order');
    }
}
